import jsPDF from "jspdf";

const COLORS = {
  primary: [124, 58, 237], // violet
  primaryDark: [91, 33, 182],
  text: [30, 41, 59],
  muted: [100, 116, 139],
  lightText: [148, 163, 184],
  border: [226, 232, 240],
  background: [248, 250, 252],
  white: [255, 255, 255],

  success: [22, 163, 74],
  successBg: [240, 253, 244],

  warning: [217, 119, 6],
  warningBg: [255, 251, 235],

  danger: [220, 38, 38],
  dangerBg: [254, 242, 242],

  info: [37, 99, 235],
  infoBg: [239, 246, 255],
};

const PAGE = {
  width: 210,
  height: 297,
  margin: 16,
};

function safeText(value, fallback = "") {
  if (value === null || value === undefined) {
    return fallback;
  }

  return String(value);
}

function clamp(value, min = 0, max = 100) {
  const number = Number(value);

  if (Number.isNaN(number)) {
    return min;
  }

  return Math.min(Math.max(number, min), max);
}

function getSkillName(skill) {
  if (typeof skill === "string") {
    return skill;
  }

  return skill?.skill || skill?.name || "Unknown skill";
}

function getSkillEvidence(skill) {
  if (typeof skill === "object") {
    return skill?.evidence || "";
  }

  return "";
}

function setTextColor(doc, color) {
  doc.setTextColor(...color);
}

function setFillColor(doc, color) {
  doc.setFillColor(...color);
}

function setDrawColor(doc, color) {
  doc.setDrawColor(...color);
}

function drawRoundedCard(doc, x, y, width, height, options = {}) {
  const { fill = COLORS.white, border = COLORS.border, radius = 4 } = options;

  setFillColor(doc, fill);
  setDrawColor(doc, border);

  doc.setLineWidth(0.25);
  doc.roundedRect(x, y, width, height, radius, radius, "FD");
}

function splitText(doc, text, width) {
  return doc.splitTextToSize(safeText(text), width);
}

function getTextHeight(doc, text, width, fontSize = 9, lineHeight = 1.35) {
  doc.setFontSize(fontSize);

  const lines = splitText(doc, text, width);

  return lines.length * fontSize * 0.3528 * lineHeight;
}

function drawLogo(doc, x, y) {
  // Vector logo mark
  setFillColor(doc, COLORS.primary);
  doc.roundedRect(x, y, 10, 10, 3, 3, "F");

  setFillColor(doc, COLORS.white);

  doc.circle(x + 5, y + 5, 2.2, "F");

  doc.setLineWidth(1);
  setDrawColor(doc, COLORS.white);

  doc.line(x + 5, y + 1.7, x + 5, y + 8.3);
  doc.line(x + 1.7, y + 5, x + 8.3, y + 5);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  setTextColor(doc, COLORS.text);

  doc.text("InterPrep", x + 14, y + 7.5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  setTextColor(doc, COLORS.muted);

  doc.text("AI Career Intelligence", x + 14, y + 11.5);
}

function drawPageHeader(doc, pageNumber, totalPages) {
  const y = 10;

  drawLogo(doc, PAGE.margin, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  setTextColor(doc, COLORS.muted);

  doc.text(
    `Page ${pageNumber} of ${totalPages}`,
    PAGE.width - PAGE.margin,
    y + 7,
    {
      align: "right",
    },
  );

  setDrawColor(doc, COLORS.border);
  doc.setLineWidth(0.25);

  doc.line(PAGE.margin, y + 16, PAGE.width - PAGE.margin, y + 16);
}

function drawFooter(doc) {
  const y = PAGE.height - 10;

  setDrawColor(doc, COLORS.border);
  doc.setLineWidth(0.25);

  doc.line(PAGE.margin, y - 5, PAGE.width - PAGE.margin, y - 5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.8);
  setTextColor(doc, COLORS.lightText);

  doc.text("Generated by InterPrep AI", PAGE.margin, y);

  doc.text(
    "Estimated match score, not a guaranteed ATS result.",
    PAGE.width - PAGE.margin,
    y,
    {
      align: "right",
    },
  );
}

function getContentBottom() {
  return PAGE.height - 18;
}

function ensureSpace(doc, currentY, requiredHeight) {
  const bottom = getContentBottom();

  if (currentY + requiredHeight <= bottom) {
    return currentY;
  }

  doc.addPage();

  return 28;
}

function addSectionTitle(doc, title, y, subtitle = "") {
  y = ensureSpace(doc, y, subtitle ? 16 : 11);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  setTextColor(doc, COLORS.text);

  doc.text(title, PAGE.margin, y);

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    setTextColor(doc, COLORS.muted);

    doc.text(subtitle, PAGE.margin, y + 5);
    return y + 10;
  }

  return y + 7;
}

function addProgressBar(doc, x, y, width, percentage, color = COLORS.primary) {
  const height = 4;

  setFillColor(doc, [241, 245, 249]);

  doc.roundedRect(x, y, width, height, 2, 2, "F");

  const filledWidth = width * (clamp(percentage) / 100);

  if (filledWidth > 0) {
    setFillColor(doc, color);

    doc.roundedRect(x, y, Math.max(filledWidth, 2), height, 2, 2, "F");
  }
}

function addMetricRow(
  doc,
  label,
  value,
  percentage,
  y,
  color = COLORS.primary,
) {
  const labelWidth = 62;
  const barWidth = 85;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  setTextColor(doc, COLORS.text);

  doc.text(label, PAGE.margin, y);

  addProgressBar(
    doc,
    PAGE.margin + labelWidth,
    y - 3,
    barWidth,
    percentage,
    color,
  );

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);

  setTextColor(doc, color);

  doc.text(
    `${Math.round(clamp(value))}%`,
    PAGE.margin + labelWidth + barWidth + 6,
    y,
  );

  return y + 9;
}

function addBulletList(doc, items, y, options = {}) {
  const {
    color = COLORS.primary,
    bullet = "•",
    fontSize = 8.5,
    gap = 5,
    maxWidth = PAGE.width - PAGE.margin * 2 - 8,
  } = options;

  if (!items?.length) {
    return y;
  }

  items.forEach((item) => {
    const text =
      typeof item === "string" ? item : item?.text || item?.name || "";

    if (!text) {
      return;
    }

    const lines = splitText(doc, text, maxWidth);

    const height = lines.length * fontSize * 0.3528 * 1.35 + gap;

    y = ensureSpace(doc, y, height);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(fontSize);

    setTextColor(doc, color);

    doc.text(bullet, PAGE.margin, y);

    doc.setFont("helvetica", "normal");
    setTextColor(doc, COLORS.text);

    doc.text(lines, PAGE.margin + 5, y);

    y += lines.length * fontSize * 0.3528 * 1.35 + gap;
  });

  return y;
}

function addSkillSection(doc, title, skills, y, options = {}) {
  const { color, background, icon } = options;

  if (!skills?.length) {
    return y;
  }

  y = ensureSpace(doc, y, 16);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);

  setTextColor(doc, color);

  doc.text(`${icon} ${title} (${skills.length})`, PAGE.margin, y);

  y += 5;

  skills.forEach((skill) => {
    const name = getSkillName(skill);
    const evidence = getSkillEvidence(skill);

    const evidenceHeight = evidence
      ? getTextHeight(doc, evidence, 152, 7.5)
      : 0;

    const cardHeight = evidenceHeight + 12;

    y = ensureSpace(doc, y, cardHeight + 3);

    drawRoundedCard(
      doc,
      PAGE.margin,
      y,
      PAGE.width - PAGE.margin * 2,
      cardHeight,
      {
        fill: background,
        border: COLORS.border,
        radius: 3,
      },
    );

    setFillColor(doc, color);

    doc.circle(PAGE.margin + 5, y + 6, 1.6, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);

    setTextColor(doc, COLORS.text);

    doc.text(name, PAGE.margin + 10, y + 7);

    if (evidence) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);

      setTextColor(doc, COLORS.muted);

      const lines = splitText(doc, evidence, 150);

      doc.text(lines, PAGE.margin + 10, y + 11);
    }

    y += cardHeight + 3;
  });

  return y + 2;
}

function addInfoCard(doc, title, value, x, y, width, options = {}) {
  const { color = COLORS.primary, subtitle = "" } = options;

  const height = subtitle ? 27 : 22;

  drawRoundedCard(doc, x, y, width, height, {
    fill: COLORS.white,
    border: COLORS.border,
    radius: 4,
  });

  setFillColor(doc, color);

  doc.roundedRect(x, y, 2.5, height, 1, 1, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  setTextColor(doc, COLORS.muted);

  doc.text(title, x + 7, y + 7);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setTextColor(doc, COLORS.text);

  doc.text(safeText(value), x + 7, y + 15);

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    setTextColor(doc, COLORS.muted);

    doc.text(subtitle, x + 7, y + 21);
  }

  return height;
}

function addParagraph(doc, title, text, y) {
  if (!text) {
    return y;
  }

  const width = PAGE.width - PAGE.margin * 2;

  const lines = splitText(doc, text, width);

  const height = lines.length * 8.5 * 0.3528 * 1.4 + 14;

  y = ensureSpace(doc, y, height);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  setTextColor(doc, COLORS.text);

  doc.text(title, PAGE.margin, y);

  y += 5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  setTextColor(doc, COLORS.muted);

  doc.text(lines, PAGE.margin, y);

  return y + lines.length * 8.5 * 0.3528 * 1.4 + 5;
}

function addScoreOverview(doc, ats, y) {
  const score = clamp(ats?.atsScore || 0);

  const cardWidth = PAGE.width - PAGE.margin * 2;

  const cardHeight = 57;

  y = ensureSpace(doc, y, cardHeight);

  drawRoundedCard(doc, PAGE.margin, y, cardWidth, cardHeight, {
    fill: COLORS.white,
    border: COLORS.border,
    radius: 5,
  });

  // Accent background
  setFillColor(doc, [245, 243, 255]);

  doc.roundedRect(PAGE.margin, y, 53, cardHeight, 5, 5, "F");

  // Score circle
  const centerX = PAGE.margin + 26.5;

  const centerY = y + 28;

  setDrawColor(doc, [221, 214, 254]);

  doc.setLineWidth(5);

  doc.circle(centerX, centerY, 16, "S");

  setDrawColor(doc, COLORS.primary);

  doc.setLineWidth(5);

  // Approximate progress using segmented arc
  const segments = 36;
  const activeSegments = Math.round((score / 100) * segments);

  for (let i = 0; i < activeSegments; i++) {
    const angle = -Math.PI / 2 + (i / segments) * Math.PI * 2;

    const nextAngle = -Math.PI / 2 + ((i + 0.72) / segments) * Math.PI * 2;

    const r = 16;

    const x1 = centerX + Math.cos(angle) * r;

    const y1 = centerY + Math.sin(angle) * r;

    const x2 = centerX + Math.cos(nextAngle) * r;

    const y2 = centerY + Math.sin(nextAngle) * r;

    doc.line(x1, y1, x2, y2);
  }

  doc.setFont("helvetica", "bold");

  doc.setFontSize(17);

  setTextColor(doc, COLORS.primaryDark);

  doc.text(`${Math.round(score)}%`, centerX, centerY + 2, {
    align: "center",
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);

  setTextColor(doc, COLORS.text);

  doc.text("ATS Match Score", PAGE.margin + 62, y + 14);

  let scoreLabel = "Needs Improvement";

  if (score >= 80) {
    scoreLabel = "Strong Match";
  } else if (score >= 65) {
    scoreLabel = "Good Match";
  } else if (score >= 50) {
    scoreLabel = "Moderate Match";
  }

  doc.setFont("helvetica", "bold");

  doc.setFontSize(8);

  setTextColor(
    doc,
    score >= 70 ? COLORS.success : score >= 50 ? COLORS.warning : COLORS.danger,
  );

  doc.text(scoreLabel, PAGE.margin + 62, y + 21);

  doc.setFont("helvetica", "normal");

  doc.setFontSize(7.5);

  setTextColor(doc, COLORS.muted);

  const description =
    "Estimated compatibility between the candidate resume and the provided job description.";

  const descriptionLines = splitText(doc, description, cardWidth - 72);

  doc.text(descriptionLines, PAGE.margin + 62, y + 28);

  return y + cardHeight + 7;
}

function addScoreBreakdown(doc, breakdown, y) {
  y = addSectionTitle(
    doc,
    "Score Breakdown",
    y,
    "How the overall match score was calculated",
  );

  const rows = [
    ["Keyword Match", breakdown?.keywordMatch],
    ["Skills Match", breakdown?.skillsMatch],
    ["Experience Alignment", breakdown?.experienceAlignment],
    ["Responsibility Alignment", breakdown?.responsibilityAlignment],
    ["Education Alignment", breakdown?.educationAlignment],
    ["Resume Quality", breakdown?.resumeQuality],
  ];

  rows.forEach(([label, value]) => {
    y = ensureSpace(doc, y, 10);

    y = addMetricRow(doc, label, value || 0, value || 0, y, COLORS.primary);
  });

  return y + 3;
}

function addExperienceSection(doc, experience, y) {
  y = addSectionTitle(doc, "Experience Alignment", y);

  const required = experience?.required_years ?? 0;

  const candidate = experience?.candidate_years ?? 0;

  const status = experience?.status || "unknown";

  const statusColor =
    status === "matched"
      ? COLORS.success
      : status === "partially_matched"
        ? COLORS.warning
        : COLORS.danger;

  const statusLabel =
    status === "matched"
      ? "Matched"
      : status === "partially_matched"
        ? "Partially Matched"
        : status === "missing"
          ? "Below Requirement"
          : "Not Available";

  const gap =
    required > candidate
      ? `${(required - candidate).toFixed(1)} year(s) below requirement`
      : "Experience requirement met";

  const cardWidth = (PAGE.width - PAGE.margin * 2 - 6) / 2;

  y = ensureSpace(doc, y, 38);

  addInfoCard(
    doc,
    "Required Experience",
    `${required} year${required === 1 ? "" : "s"}`,
    PAGE.margin,
    y,
    cardWidth,
    {
      color: COLORS.info,
    },
  );

  addInfoCard(
    doc,
    "Candidate Experience",
    `${candidate} year${candidate === 1 ? "" : "s"}`,
    PAGE.margin + cardWidth + 6,
    y,
    cardWidth,
    {
      color: statusColor,
    },
  );

  y += 33;

  drawRoundedCard(doc, PAGE.margin, y, PAGE.width - PAGE.margin * 2, 25, {
    fill:
      status === "matched"
        ? COLORS.successBg
        : status === "partially_matched"
          ? COLORS.warningBg
          : COLORS.dangerBg,
    border: COLORS.border,
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);

  setTextColor(doc, statusColor);

  doc.text(statusLabel, PAGE.margin + 7, y + 9);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);

  setTextColor(doc, COLORS.text);

  doc.text(gap, PAGE.margin + 7, y + 17);

  y += 31;

  y = addParagraph(doc, "AI Assessment", experience?.evidence, y);

  return y + 3;
}

function addEducationSection(doc, education, y) {
  y = addSectionTitle(doc, "Education Alignment", y);

  const required = education?.required;

  const matched = education?.matched;

  const statusColor = matched
    ? COLORS.success
    : required
      ? COLORS.danger
      : COLORS.info;

  const statusText = !required
    ? "Not required"
    : matched
      ? "Requirement matched"
      : "Requirement not matched";

  y = ensureSpace(doc, y, 31);

  drawRoundedCard(doc, PAGE.margin, y, PAGE.width - PAGE.margin * 2, 27, {
    fill: matched ? COLORS.successBg : COLORS.background,
    border: COLORS.border,
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);

  setTextColor(doc, statusColor);

  doc.text(statusText, PAGE.margin + 7, y + 9);

  if (education?.evidence) {
    doc.setFont("helvetica", "normal");

    doc.setFontSize(7.5);

    setTextColor(doc, COLORS.text);

    const lines = splitText(
      doc,
      education.evidence,
      PAGE.width - PAGE.margin * 2 - 14,
    );

    doc.text(lines, PAGE.margin + 7, y + 16);
  }

  return y + 34;
}

function addResponsibilitiesSection(doc, responsibilities, y) {
  y = addSectionTitle(
    doc,
    "Responsibility Alignment",
    y,
    "Comparison of job responsibilities with resume evidence",
  );

  const total = responsibilities?.total || 0;

  const matched = responsibilities?.matched || 0;

  const partial = responsibilities?.partially_matched || 0;

  const missing = responsibilities?.missing || 0;

  const score = total > 0 ? ((matched + partial * 0.5) / total) * 100 : 0;

  y = ensureSpace(doc, y, 24);

  const boxWidth = (PAGE.width - PAGE.margin * 2 - 9) / 4;

  const items = [
    ["Total", total, COLORS.info],
    ["Matched", matched, COLORS.success],
    ["Partial", partial, COLORS.warning],
    ["Missing", missing, COLORS.danger],
  ];

  items.forEach(([label, value, color], index) => {
    addInfoCard(
      doc,
      label,
      String(value),
      PAGE.margin + index * (boxWidth + 3),
      y,
      boxWidth,
      {
        color,
      },
    );
  });

  y += 34;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);

  setTextColor(doc, COLORS.text);

  doc.text(`Responsibility Match: ${Math.round(score)}%`, PAGE.margin, y);

  addProgressBar(doc, PAGE.margin + 55, y - 3, 105, score, COLORS.primary);

  y += 10;

  const details = responsibilities?.details || [];

  details.forEach((item) => {
    const responsibility = item?.responsibility || "Responsibility";

    const status = item?.status || "unknown";

    const evidence = item?.evidence || "";

    const statusColor =
      status === "matched"
        ? COLORS.success
        : status === "partially_matched"
          ? COLORS.warning
          : COLORS.danger;

    const statusLabel =
      status === "matched"
        ? "MATCHED"
        : status === "partially_matched"
          ? "PARTIAL"
          : "MISSING";

    const evidenceLines = evidence ? splitText(doc, evidence, 142) : [];

    const height = 16 + evidenceLines.length * 7.5 * 0.3528 * 1.35;

    y = ensureSpace(doc, y, height + 3);

    drawRoundedCard(doc, PAGE.margin, y, PAGE.width - PAGE.margin * 2, height, {
      fill: COLORS.white,
      border: COLORS.border,
    });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);

    setTextColor(doc, COLORS.text);

    const responsibilityLines = splitText(doc, responsibility, 105);

    doc.text(responsibilityLines, PAGE.margin + 7, y + 7);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);

    setTextColor(doc, statusColor);

    doc.text(statusLabel, PAGE.width - PAGE.margin - 7, y + 7, {
      align: "right",
    });

    if (evidence) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.2);

      setTextColor(doc, COLORS.muted);

      doc.text(
        evidenceLines,
        PAGE.margin + 7,
        y + 7 + responsibilityLines.length * 3.8 + 4,
      );
    }

    y += height + 3;
  });

  return y + 2;
}

function addResumeQualitySection(doc, resumeQuality, y) {
  y = addSectionTitle(doc, "Resume Quality", y);

  const score = clamp(resumeQuality?.score || 0);

  y = ensureSpace(doc, y, 35);

  drawRoundedCard(doc, PAGE.margin, y, PAGE.width - PAGE.margin * 2, 31, {
    fill: COLORS.white,
    border: COLORS.border,
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);

  setTextColor(doc, COLORS.primary);

  doc.text(`${Math.round(score)}/100`, PAGE.margin + 8, y + 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);

  setTextColor(doc, COLORS.muted);

  doc.text("Resume Quality Score", PAGE.margin + 8, y + 21);

  addProgressBar(doc, PAGE.margin + 55, y + 12, 115, score, COLORS.primary);

  y += 39;

  if (resumeQuality?.strengths?.length) {
    y = addSkillSection(doc, "What Works Well", resumeQuality.strengths, y, {
      color: COLORS.success,
      background: COLORS.successBg,
      icon: "✓",
    });
  }

  if (resumeQuality?.improvements?.length) {
    y = addSkillSection(
      doc,
      "What Can Be Improved",
      resumeQuality.improvements,
      y,
      {
        color: COLORS.warning,
        background: COLORS.warningBg,
        icon: "!",
      },
    );
  }

  return y;
}

function addTwoColumnLists(
  doc,
  leftTitle,
  leftItems,
  rightTitle,
  rightItems,
  y,
) {
  const gap = 6;

  const width = (PAGE.width - PAGE.margin * 2 - gap) / 2;

  const leftHeight = 18 + (leftItems?.length || 0) * 11;

  const rightHeight = 18 + (rightItems?.length || 0) * 11;

  const height = Math.max(leftHeight, rightHeight, 30);

  y = ensureSpace(doc, y, height);

  drawRoundedCard(doc, PAGE.margin, y, width, height, {
    fill: COLORS.white,
    border: COLORS.border,
  });

  drawRoundedCard(doc, PAGE.margin + width + gap, y, width, height, {
    fill: COLORS.white,
    border: COLORS.border,
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);

  setTextColor(doc, COLORS.success);

  doc.text(leftTitle, PAGE.margin + 7, y + 9);

  setTextColor(doc, COLORS.danger);

  doc.text(rightTitle, PAGE.margin + width + gap + 7, y + 9);

  const drawItems = (items, x, color) => {
    if (!items?.length) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      setTextColor(doc, COLORS.muted);

      doc.text("None identified", x, y + 18);

      return;
    }

    items.forEach((item, index) => {
      const text =
        typeof item === "string" ? item : item?.text || item?.name || "";

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);

      setTextColor(doc, color);

      doc.text("•", x, y + 18 + index * 11);

      doc.setFont("helvetica", "normal");

      setTextColor(doc, COLORS.text);

      const lines = splitText(doc, text, width - 16);

      doc.text(lines[0] || "", x + 5, y + 18 + index * 11);
    });
  };

  drawItems(leftItems, PAGE.margin + 7, COLORS.success);

  drawItems(rightItems, PAGE.margin + width + gap + 7, COLORS.danger);

  return y + height + 7;
}

function addRecommendations(doc, recommendations, y) {
  if (!recommendations?.length) {
    return y;
  }

  y = addSectionTitle(
    doc,
    "AI Improvement Plan",
    y,
    "Practical actions to improve the resume-job match",
  );

  recommendations.forEach((recommendation, index) => {
    const text =
      typeof recommendation === "string"
        ? recommendation
        : recommendation?.text || recommendation?.recommendation || "";

    if (!text) {
      return;
    }

    const lines = splitText(doc, text, PAGE.width - PAGE.margin * 2 - 18);

    const height = Math.max(15, lines.length * 8 * 0.3528 * 1.35 + 10);

    y = ensureSpace(doc, y, height + 3);

    drawRoundedCard(doc, PAGE.margin, y, PAGE.width - PAGE.margin * 2, height, {
      fill: COLORS.white,
      border: COLORS.border,
    });

    setFillColor(doc, COLORS.primary);

    doc.circle(PAGE.margin + 8, y + 8, 4, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);

    setTextColor(doc, COLORS.white);

    doc.text(String(index + 1), PAGE.margin + 8, y + 10.2, {
      align: "center",
    });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);

    setTextColor(doc, COLORS.text);

    doc.text(lines, PAGE.margin + 16, y + 8);

    y += height + 3;
  });

  return y + 2;
}

function addReportCover(doc, data, resumeName) {
  const ats = data?.ats || {};
  const score = clamp(ats?.atsScore || 0);

  // Top brand area
  drawLogo(doc, PAGE.margin, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);

  setTextColor(doc, COLORS.muted);

  doc.text(
    new Date().toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    }),
    PAGE.width - PAGE.margin,
    24,
    {
      align: "right",
    },
  );

  // Main title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(25);

  setTextColor(doc, COLORS.text);

  doc.text("AI Resume Analysis", PAGE.margin, 58);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  setTextColor(doc, COLORS.muted);

  doc.text("Resume-to-job compatibility report", PAGE.margin, 67);

  // Resume information
  if (resumeName) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);

    setTextColor(doc, COLORS.text);

    doc.text("Resume", PAGE.margin, 83);

    doc.setFont("helvetica", "normal");

    setTextColor(doc, COLORS.muted);

    doc.text(resumeName, PAGE.margin, 89);
  }

  // Big score card
  drawRoundedCard(doc, PAGE.margin, 105, PAGE.width - PAGE.margin * 2, 65, {
    fill: COLORS.background,
    border: COLORS.border,
    radius: 6,
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);

  setTextColor(doc, COLORS.muted);

  doc.text("OVERALL ATS MATCH", PAGE.margin + 10, 119);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(35);

  setTextColor(doc, COLORS.primary);

  doc.text(`${Math.round(score)}%`, PAGE.margin + 10, 151);

  let scoreLabel = "Needs Improvement";

  if (score >= 80) {
    scoreLabel = "Strong Match";
  } else if (score >= 65) {
    scoreLabel = "Good Match";
  } else if (score >= 50) {
    scoreLabel = "Moderate Match";
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);

  setTextColor(
    doc,
    score >= 70 ? COLORS.success : score >= 50 ? COLORS.warning : COLORS.danger,
  );

  doc.text(scoreLabel, PAGE.margin + 68, 130);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);

  setTextColor(doc, COLORS.muted);

  const summary =
    "This report analyzes how closely the candidate's resume aligns with the provided job description across skills, experience, responsibilities, education and resume quality.";

  doc.text(splitText(doc, summary, 112), PAGE.margin + 68, 139);

  // Footer note
  drawRoundedCard(doc, PAGE.margin, 190, PAGE.width - PAGE.margin * 2, 34, {
    fill: [245, 243, 255],
    border: [221, 214, 254],
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);

  setTextColor(doc, COLORS.primaryDark);

  doc.text("Important", PAGE.margin + 8, 201);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);

  setTextColor(doc, COLORS.text);

  doc.text(
    splitText(
      doc,
      "ATS scores are estimates based on the supplied resume and job description. Different applicant tracking systems may evaluate resumes differently.",
      PAGE.width - PAGE.margin * 2 - 16,
    ),
    PAGE.margin + 8,
    208,
  );

  // Cover bottom
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);

  setTextColor(doc, COLORS.lightText);

  doc.text("InterPrep • AI-powered career intelligence", PAGE.width / 2, 275, {
    align: "center",
  });

  return 245;
}

/**
 * Generates a professional structured PDF report.
 *
 * @param {Object} analysisData - Analysis response or analysis.data object
 * @param {Object} options
 * @param {string} options.resumeName - Optional uploaded resume filename
 */
export async function generateAnalysisReport(analysisData, options = {}) {
  if (!analysisData) {
    throw new Error("Analysis data is required to generate the report.");
  }

  const data = analysisData?.data || analysisData;

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  const resumeName = options?.resumeName || "";

  // --------------------------------------------------
  // COVER PAGE
  // --------------------------------------------------

  addReportCover(doc, data, resumeName);

  // --------------------------------------------------
  // PAGE 2
  // --------------------------------------------------

  doc.addPage();

  let y = 31;

  y = addSectionTitle(
    doc,
    "Analysis Overview",
    y,
    "A detailed breakdown of resume compatibility",
  );

  y = addScoreOverview(doc, data?.ats, y);

  y = addScoreBreakdown(doc, data?.ats?.breakdown, y);

  // --------------------------------------------------
  // SKILLS
  // --------------------------------------------------

  y = addSectionTitle(
    doc,
    "Skills Analysis",
    y,
    "Skills identified from the resume and job description",
  );

  y = addSkillSection(doc, "Matched Skills", data?.matched_skills, y, {
    color: COLORS.success,
    background: COLORS.successBg,
    icon: "✓",
  });

  y = addSkillSection(
    doc,
    "Partially Matched",
    data?.partially_matched_skills,
    y,
    {
      color: COLORS.warning,
      background: COLORS.warningBg,
      icon: "◐",
    },
  );

  y = addSkillSection(doc, "Missing Skills", data?.missing_skills, y, {
    color: COLORS.danger,
    background: COLORS.dangerBg,
    icon: "✕",
  });

  // --------------------------------------------------
  // EXPERIENCE
  // --------------------------------------------------

  y = addExperienceSection(doc, data?.experience, y);

  // --------------------------------------------------
  // EDUCATION
  // --------------------------------------------------

  y = addEducationSection(doc, data?.education, y);

  // --------------------------------------------------
  // RESPONSIBILITIES
  // --------------------------------------------------

  y = addResponsibilitiesSection(doc, data?.responsibilities, y);

  // --------------------------------------------------
  // ALIGNMENT SUMMARY
  // --------------------------------------------------

  y = addParagraph(
    doc,
    "Experience Alignment Summary",
    data?.experience_alignment,
    y,
  );

  y = addParagraph(
    doc,
    "Responsibility Alignment Summary",
    data?.responsibility_alignment,
    y,
  );

  // --------------------------------------------------
  // STRENGTHS / WEAKNESSES
  // --------------------------------------------------

  y = ensureSpace(doc, y, 60);

  y = addSectionTitle(
    doc,
    "Candidate Assessment",
    y,
    "Key strengths and potential gaps identified by the analysis",
  );

  y = addTwoColumnLists(
    doc,
    "Strengths",
    data?.strengths || [],
    "Weaknesses",
    data?.weaknesses || [],
    y,
  );

  // --------------------------------------------------
  // RESUME QUALITY
  // --------------------------------------------------

  y = addResumeQualitySection(doc, data?.resume_quality, y);

  // --------------------------------------------------
  // RECOMMENDATIONS
  // --------------------------------------------------

  y = addRecommendations(doc, data?.recommendations, y);

  // --------------------------------------------------
  // PAGE NUMBERS + FOOTERS
  // --------------------------------------------------

  const totalPages = doc.getNumberOfPages();

  for (let page = 1; page <= totalPages; page++) {
    doc.setPage(page);

    if (page > 1) {
      drawPageHeader(doc, page, totalPages);
    }

    drawFooter(doc);
  }

  // --------------------------------------------------
  // DOWNLOAD
  // --------------------------------------------------

  const date = new Date().toISOString().split("T")[0];

  const filename = `InterPrep-Resume-Analysis-${date}.pdf`;

  doc.save(filename);

  return filename;
}

export default generateAnalysisReport;
